behaviors:
    AdvancedNavigation:
        trainer_type: ppo
        hyperparameters:
            batch_size: 512 
            buffer_size: 10240
            learning_rate: 0.0003
            beta: 0.005 #Entropy Coefficient
            epsilon: 0.2 # Clip range
            lambd: 0.95 
            num_epoch: 3
            learning_rate_schedule: linear
            beta_schedule: linear
        network_settings:
            normalize: false
            hidden_units: 512
            num_layers: 3
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
            curiosity:
                gamma: 0.99
                strength: 0.03
        keep_checkpoints: 10
        checkpoint_interval: 1000000
        max_steps: 10000000
        time_horizon: 64
        summary_freq: 100000
        threaded: true
# Curriculum learning: uses level_complexity which in the code changes the generation parameters
# measures progress (steps / total steps). Can't use reward as it changes per lesson / layout.
environment_parameters:
  level_complexity:
    curriculum:
      - name: Lesson0 # 2 rooms, no branches. 
        completion_criteria:
          measure: progress
          behavior: AdvancedNavigation
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
        value: 0.0
      - name: Lesson1 # 3 rooms, no branches. 
        completion_criteria:
          measure: progress
          behavior: AdvancedNavigation
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.2
        value: 1.0
      - name: Lesson2 # 3 rooms, 1 branch. 
        completion_criteria:
          measure: progress
          behavior: AdvancedNavigation
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 2.0
      - name: Lesson3 # 4 rooms, 2 branches of length 1. 
        completion_criteria:
          measure: progress
          behavior: AdvancedNavigation
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.7
        value: 3.0
      - name: Lesson4 # 4 rooms, 2 branches of length 2. 
        completion_criteria:
          measure: progress
          behavior: AdvancedNavigation
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value: 4.0
      - name: Lesson5 # 4 rooms, 2 branches of length 3. 
        value: 5.0



