behaviors:
    Stage_2:
        trainer_type: sac
        hyperparameters:
            batch_size: 512
            buffer_size: 100000
            learning_rate: 0.0005
            tau: 0.005
            steps_per_update: 10.0
            save_replay_buffer: false
            buffer_init_steps: 5000
            init_entcoef: 0.5
            learning_rate_schedule: constant
        network_settings:
            normalize: false
            hidden_units: 256
            num_layers: 2
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
            curiosity:
                gamma: 0.99
                strength: 0.03   
        keep_checkpoints: 5
        max_steps: 500000
        time_horizon: 128
        summary_freq: 100000
        threaded: true



